spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update #create-drop
      format-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

# expose all spring actuator endpoints:
management:
  endpoints:
    web:
      exposure:
        include: "*"